# Generated by Django 3.2.16 on 2022-11-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha en la que se requiere agendar el servicio.')),
                ('hora', models.TimeField(help_text='Hora en la que se requiere agendar el servicio.')),
                ('fecha_hora', models.DateTimeField(blank=True, help_text='Fecha y hora en la que se requiere agendar el servicio.', null=True)),
                ('lat_origen', models.SmallIntegerField()),
                ('lng_origen', models.SmallIntegerField()),
                ('destino', models.CharField(max_length=70)),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se crea el agendamiento del servicio.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_cliente', to='clientes.cliente')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_conductor', to='conductores.conductor')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
